import Head from 'next/head'
import Header from '../components/Header/Header'
import Layout from '../components/HomeLayout/HomeLayout'
import NavigationBar from '../components/NavigationBar/NavigationBar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NO BROKER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout />
      </main>

    </div>
  )
}
